"""nakit iade ve indirim orani sutunlari eklendi

Revision ID: 348b48b28c29
Revises: c9d2e4a17b30
Create Date: 2026-08-24 18:59:42.081684

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '348b48b28c29'
down_revision: Union[str, Sequence[str], None] = 'c9d2e4a17b30'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('kampanyalar', sa.Column('nakit_iade_orani', sa.Float(), nullable=True))
    op.add_column('kampanyalar', sa.Column('indirim_orani_percent', sa.Float(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('kampanyalar', 'indirim_orani_percent')
    op.drop_column('kampanyalar', 'nakit_iade_orani')
    # ### end Alembic commands ###
