"""kullanicilar tablosu eklendi

Revision ID: 3f40c72cb489
Revises: 86a1d27e0191
Create Date: 2026-08-01 00:14:42.437600

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3f40c72cb489'
down_revision: Union[str, Sequence[str], None] = '86a1d27e0191'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('kullanicilar',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('kullanici_adi', sa.String(length=100), nullable=False),
    sa.Column('sifre_hash', sa.String(length=100), nullable=False),
    sa.Column('rol', sa.String(length=50), nullable=False),
    sa.Column('aktif', sa.Boolean(), nullable=True),
    sa.Column('olusturulma', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_kullanicilar_kullanici_adi'), 'kullanicilar', ['kullanici_adi'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_kullanicilar_kullanici_adi'), table_name='kullanicilar')
    op.drop_table('kullanicilar')
    # ### end Alembic commands ###
