"""kampanyalar ve audit_kayitlari tablolari

Revision ID: 6c6458e33bd5
Revises: 
Create Date: 2026-07-27 20:44:53.883231

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6c6458e33bd5'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('audit_kayitlari',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('kullanici', sa.String(length=100), nullable=True),
    sa.Column('rol', sa.String(length=50), nullable=True),
    sa.Column('uc_nokta', sa.String(length=100), nullable=True),
    sa.Column('soru', sa.String(length=1000), nullable=True),
    sa.Column('intent', sa.String(length=50), nullable=True),
    sa.Column('intent_confidence', sa.Float(), nullable=True),
    sa.Column('cagrilan_arac', sa.String(length=50), nullable=True),
    sa.Column('sql_sorgusu', sa.String(length=2000), nullable=True),
    sa.Column('latency_ms', sa.Integer(), nullable=True),
    sa.Column('cache_hit', sa.Boolean(), nullable=True),
    sa.Column('zaman', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_audit_kayitlari_kullanici'), 'audit_kayitlari', ['kullanici'], unique=False)
    op.create_index(op.f('ix_audit_kayitlari_zaman'), 'audit_kayitlari', ['zaman'], unique=False)
    op.create_table('kampanyalar',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('banka', sa.String(length=100), nullable=False),
    sa.Column('kampanya_adi', sa.String(length=300), nullable=False),
    sa.Column('kampanya_turu', sa.String(length=100), nullable=True),
    sa.Column('kar_payi_orani_percent', sa.Float(), nullable=True),
    sa.Column('kar_payi_orani_decimal', sa.Float(), nullable=True),
    sa.Column('vade_ay', sa.Integer(), nullable=True),
    sa.Column('finansman_tutari', sa.Float(), nullable=True),
    sa.Column('odul_miktari', sa.Float(), nullable=True),
    sa.Column('odul_birimi', sa.String(length=50), nullable=True),
    sa.Column('kampanya_avantaji', sa.String(length=1000), nullable=True),
    sa.Column('masraf_durumu', sa.String(length=300), nullable=True),
    sa.Column('tahsis_ucreti', sa.Float(), nullable=True),
    sa.Column('kampanya_baslangic', sa.Date(), nullable=True),
    sa.Column('kampanya_bitis', sa.Date(), nullable=True),
    sa.Column('durum', sa.String(length=20), nullable=True),
    sa.Column('hedef_kitle', sa.String(length=300), nullable=True),
    sa.Column('kaynak_url', sa.String(length=700), nullable=False),
    sa.Column('belge_tarihi', sa.Date(), nullable=True),
    sa.Column('confidence', sa.Float(), nullable=True),
    sa.Column('cikarim_yontemi', sa.String(length=20), nullable=True),
    sa.Column('alan_belirtilmemis', sa.JSON(), nullable=True),
    sa.Column('olusturulma', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('guncellenme', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_kampanyalar_banka'), 'kampanyalar', ['banka'], unique=False)
    op.create_index(op.f('ix_kampanyalar_durum'), 'kampanyalar', ['durum'], unique=False)
    op.create_index(op.f('ix_kampanyalar_kampanya_turu'), 'kampanyalar', ['kampanya_turu'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_kampanyalar_kampanya_turu'), table_name='kampanyalar')
    op.drop_index(op.f('ix_kampanyalar_durum'), table_name='kampanyalar')
    op.drop_index(op.f('ix_kampanyalar_banka'), table_name='kampanyalar')
    op.drop_table('kampanyalar')
    op.drop_index(op.f('ix_audit_kayitlari_zaman'), table_name='audit_kayitlari')
    op.drop_index(op.f('ix_audit_kayitlari_kullanici'), table_name='audit_kayitlari')
    op.drop_table('audit_kayitlari')
    # ### end Alembic commands ###
