"""taksit_sayisi ve erteleme_suresi_ay alanlari eklendi

Revision ID: 86a1d27e0191
Revises: 6c6458e33bd5
Create Date: 2026-07-31 21:05:07.395553

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '86a1d27e0191'
down_revision: Union[str, Sequence[str], None] = '6c6458e33bd5'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('kampanyalar', sa.Column('taksit_sayisi', sa.Integer(), nullable=True))
    op.add_column('kampanyalar', sa.Column('erteleme_suresi_ay', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('kampanyalar', 'erteleme_suresi_ay')
    op.drop_column('kampanyalar', 'taksit_sayisi')
    # ### end Alembic commands ###
